/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import '@stencil/redux';
import {
  ActiveRouter,
  MatchResults,
} from '@stencil/router';
import {
  Post,
} from './app-types';


export namespace Components {

  interface AppDatetime {
    'date': Date;
    'format': string;
    'type': 'from-now' | 'formatted';
  }
  interface AppDatetimeAttributes extends StencilHTMLAttributes {
    'date'?: Date;
    'format'?: string;
    'type'?: 'from-now' | 'formatted';
  }

  interface AppFooter {}
  interface AppFooterAttributes extends StencilHTMLAttributes {}

  interface AppHeader {
    'router': ActiveRouter;
  }
  interface AppHeaderAttributes extends StencilHTMLAttributes {
    'router'?: ActiveRouter;
  }

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppLinkbutton {
    'arrow': 'left' | 'right';
    'url': string;
  }
  interface AppLinkbuttonAttributes extends StencilHTMLAttributes {
    'arrow'?: 'left' | 'right';
    'url'?: string;
  }

  interface AppNotFound {}
  interface AppNotFoundAttributes extends StencilHTMLAttributes {}

  interface AppPost {
    'match': MatchResults;
  }
  interface AppPostAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppPosts {
    'posts': Array<Post>;
  }
  interface AppPostsAttributes extends StencilHTMLAttributes {
    'posts'?: Array<Post>;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppDatetime': Components.AppDatetime;
    'AppFooter': Components.AppFooter;
    'AppHeader': Components.AppHeader;
    'AppHome': Components.AppHome;
    'AppLinkbutton': Components.AppLinkbutton;
    'AppNotFound': Components.AppNotFound;
    'AppPost': Components.AppPost;
    'AppPosts': Components.AppPosts;
    'AppRoot': Components.AppRoot;
  }

  interface StencilIntrinsicElements {
    'app-datetime': Components.AppDatetimeAttributes;
    'app-footer': Components.AppFooterAttributes;
    'app-header': Components.AppHeaderAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-linkbutton': Components.AppLinkbuttonAttributes;
    'app-not-found': Components.AppNotFoundAttributes;
    'app-post': Components.AppPostAttributes;
    'app-posts': Components.AppPostsAttributes;
    'app-root': Components.AppRootAttributes;
  }


  interface HTMLAppDatetimeElement extends Components.AppDatetime, HTMLStencilElement {}
  var HTMLAppDatetimeElement: {
    prototype: HTMLAppDatetimeElement;
    new (): HTMLAppDatetimeElement;
  };

  interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {}
  var HTMLAppFooterElement: {
    prototype: HTMLAppFooterElement;
    new (): HTMLAppFooterElement;
  };

  interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {}
  var HTMLAppHeaderElement: {
    prototype: HTMLAppHeaderElement;
    new (): HTMLAppHeaderElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppLinkbuttonElement extends Components.AppLinkbutton, HTMLStencilElement {}
  var HTMLAppLinkbuttonElement: {
    prototype: HTMLAppLinkbuttonElement;
    new (): HTMLAppLinkbuttonElement;
  };

  interface HTMLAppNotFoundElement extends Components.AppNotFound, HTMLStencilElement {}
  var HTMLAppNotFoundElement: {
    prototype: HTMLAppNotFoundElement;
    new (): HTMLAppNotFoundElement;
  };

  interface HTMLAppPostElement extends Components.AppPost, HTMLStencilElement {}
  var HTMLAppPostElement: {
    prototype: HTMLAppPostElement;
    new (): HTMLAppPostElement;
  };

  interface HTMLAppPostsElement extends Components.AppPosts, HTMLStencilElement {}
  var HTMLAppPostsElement: {
    prototype: HTMLAppPostsElement;
    new (): HTMLAppPostsElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLElementTagNameMap {
    'app-datetime': HTMLAppDatetimeElement
    'app-footer': HTMLAppFooterElement
    'app-header': HTMLAppHeaderElement
    'app-home': HTMLAppHomeElement
    'app-linkbutton': HTMLAppLinkbuttonElement
    'app-not-found': HTMLAppNotFoundElement
    'app-post': HTMLAppPostElement
    'app-posts': HTMLAppPostsElement
    'app-root': HTMLAppRootElement
  }

  interface ElementTagNameMap {
    'app-datetime': HTMLAppDatetimeElement;
    'app-footer': HTMLAppFooterElement;
    'app-header': HTMLAppHeaderElement;
    'app-home': HTMLAppHomeElement;
    'app-linkbutton': HTMLAppLinkbuttonElement;
    'app-not-found': HTMLAppNotFoundElement;
    'app-post': HTMLAppPostElement;
    'app-posts': HTMLAppPostsElement;
    'app-root': HTMLAppRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
